<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>businessrule</name>
  <uuid>4b3fefc1-adb5-4d5a-934d-4a3f862404da</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input 
then
	set decision to "working" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
